POST http://localhost:8080/api/test
Content-Type: application/json

{
    "test": "CMC-23"
    "test": "route test"
    
}

###

POST http://localhost:8080/routes/api/months
Content-Type: application/json

{
    "month": "September"
}

###
POST https://banyan-cmc-backend.herokuapp.com/api/month
Content-Type: application/json

{
"month": "October",
"year": 2021,
"introductions": {
    "name": "Austin",
    "introDescription": "COO",
    "introImage": ""
},
"trainings": {
    "trainingTitle": "Mindfulness",
    "presenter": "Julie Landers",
    "trainingDescription": "a training on mindfulness",
    "role": "re-entry mananger"
},
"otherNotes": "This is finally working"   
}

###

GET https://banyan-cmc-backend.herokuapp.com/api/month
Content-Type: application/json

{
    
}

###
POST http://localhost:8080/routes/api/months
Content-Type: application/json

{
    "month": "August"
}

###
POST http://localhost:8080/api/test/login
Content-Type: application/json

{
    "email": "test@email.com",
    "password": "12345"
}

###
POST http://localhost:8080/routes/api/months
Content-Type: application/json

{
    "month": "October"
}

###

GET http://localhost:8080/api/months
Content-Type: application/json

{
    "months": "August"
}

###
POST http://localhost:8080/api/months
Content-Type: application/json

{
    "months": "april"
    
}

###

GET http://localhost:8080/api/months
Content-Type: application/json

{
    "months": "april"
}

###
POST http://localhost:8080/api/month
Content-Type: application/json

{
   "month": "January",
   "year": 2021,
   "introductions": {
    "name": "Shandea Hardin",
    "introDescription": "I hope this works",
    "introImage": ""
   }
}