POST http://localhost:8080/api/test
Content-Type: application/json

{
    "test": "CMC-23"
    "test": "route test"
    
}

###

POST http://localhost:8080/routes/api/months.js
Content-Type: application/json

{
    "month": "September"
}

###
POST http://localhost:8080/api/months
Content-Type: application/json

{
    "months": "april"
    
}

###

GET http://localhost:8080/api/months
Content-Type: application/json

{
    "months": "Previous Months test"
}